version: "3.8"

services:
  chroma:
    image: chromadb/chroma:1.0.16
    container_name: chroma
    ports:
      - "8000:8000"
    environment:
      IS_PERSISTENT: "TRUE"
    volumes:
      # Mount local ./data/index to container's storage path
      - ./data/index:/chroma/chroma
    restart: unless-stopped
